version: "3"
services:
  gql-server:
    network_mode: host
    build:
      context: .
      dockerfile: cmd/gqlServer/Dockerfile
    ports:
      - "8080:8080"
    restart:  on-failure
  user-service:
    network_mode: host
    build:
      context: .
      dockerfile: cmd/userService/Dockerfile
      args:
        MONGO_CONNECT_STRING: ${MONGO_CONNECT_STRING}
    ports:
      - "50051:50051"
    restart: on-failure