// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package item

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryItemReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryItemReq) Reset()         { *m = QueryItemReq{} }
func (m *QueryItemReq) String() string { return proto.CompactTextString(m) }
func (*QueryItemReq) ProtoMessage()    {}
func (*QueryItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *QueryItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryItemReq.Unmarshal(m, b)
}
func (m *QueryItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryItemReq.Marshal(b, m, deterministic)
}
func (m *QueryItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryItemReq.Merge(m, src)
}
func (m *QueryItemReq) XXX_Size() int {
	return xxx_messageInfo_QueryItemReq.Size(m)
}
func (m *QueryItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryItemReq proto.InternalMessageInfo

func (m *QueryItemReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryItemRes struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64              `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryItemRes) Reset()         { *m = QueryItemRes{} }
func (m *QueryItemRes) String() string { return proto.CompactTextString(m) }
func (*QueryItemRes) ProtoMessage()    {}
func (*QueryItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *QueryItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryItemRes.Unmarshal(m, b)
}
func (m *QueryItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryItemRes.Marshal(b, m, deterministic)
}
func (m *QueryItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryItemRes.Merge(m, src)
}
func (m *QueryItemRes) XXX_Size() int {
	return xxx_messageInfo_QueryItemRes.Size(m)
}
func (m *QueryItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryItemRes proto.InternalMessageInfo

func (m *QueryItemRes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryItemRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueryItemRes) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *QueryItemRes) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *QueryItemRes) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateItemReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemReq) Reset()         { *m = CreateItemReq{} }
func (m *CreateItemReq) String() string { return proto.CompactTextString(m) }
func (*CreateItemReq) ProtoMessage()    {}
func (*CreateItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *CreateItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemReq.Unmarshal(m, b)
}
func (m *CreateItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemReq.Marshal(b, m, deterministic)
}
func (m *CreateItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemReq.Merge(m, src)
}
func (m *CreateItemReq) XXX_Size() int {
	return xxx_messageInfo_CreateItemReq.Size(m)
}
func (m *CreateItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemReq proto.InternalMessageInfo

func (m *CreateItemReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateItemReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateItemReq) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryItemReq)(nil), "item.QueryItemReq")
	proto.RegisterType((*QueryItemRes)(nil), "item.QueryItemRes")
	proto.RegisterType((*CreateItemReq)(nil), "item.CreateItemReq")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x34, 0x45, 0xea, 0xb5, 0x30, 0x1c, 0x0c, 0x56, 0x06, 0x88, 0x32, 0x65, 0x72,
	0xa5, 0x22, 0x06, 0x46, 0xc4, 0xc4, 0x48, 0xc4, 0xc6, 0x80, 0xd2, 0xe4, 0xa8, 0x2c, 0xd5, 0x75,
	0x70, 0x2e, 0x48, 0xfc, 0x20, 0xfe, 0x27, 0xaa, 0x53, 0x8b, 0x84, 0x8f, 0x6e, 0x77, 0xaf, 0x5f,
	0x4b, 0xcf, 0x73, 0x00, 0x9a, 0xc9, 0xa8, 0xc6, 0x59, 0xb6, 0x18, 0xef, 0xe7, 0xe4, 0x6a, 0x63,
	0xed, 0x66, 0x4b, 0x4b, 0x9f, 0xad, 0xbb, 0xd7, 0x25, 0x6b, 0x43, 0x2d, 0x97, 0xa6, 0xe9, 0x6b,
	0xd9, 0x25, 0x2c, 0x1e, 0x3b, 0x72, 0x1f, 0x0f, 0x4c, 0xa6, 0xa0, 0x37, 0x3c, 0x83, 0x48, 0xd7,
	0x52, 0xa4, 0x22, 0x9f, 0x15, 0x91, 0xae, 0xb3, 0x4f, 0x31, 0x2a, 0xb4, 0x3f, 0x0b, 0x88, 0x10,
	0xef, 0x4a, 0x43, 0x32, 0xf2, 0x89, 0x9f, 0x31, 0x85, 0x79, 0x4d, 0x6d, 0xe5, 0x74, 0xc3, 0xda,
	0xee, 0xe4, 0xc4, 0x3f, 0x0d, 0x23, 0xbc, 0x80, 0x69, 0xe3, 0x74, 0x45, 0x32, 0x4e, 0x45, 0x2e,
	0x8a, 0x7e, 0xc1, 0x5b, 0x80, 0xca, 0x51, 0xc9, 0x54, 0xbf, 0x94, 0x2c, 0xa7, 0xa9, 0xc8, 0xe7,
	0xab, 0x44, 0xf5, 0x0a, 0x2a, 0x28, 0xa8, 0xa7, 0xa0, 0x50, 0xcc, 0x0e, 0xed, 0x3b, 0xce, 0x9e,
	0xe1, 0xf4, 0xde, 0x2f, 0x41, 0x24, 0x70, 0x89, 0xff, 0xb9, 0xa2, 0x23, 0x5c, 0x93, 0x01, 0xd7,
	0xaa, 0x83, 0xc5, 0x41, 0xdf, 0x6e, 0xdf, 0xc9, 0xa1, 0x82, 0x78, 0xbf, 0x23, 0x2a, 0x7f, 0xf0,
	0xe1, 0x01, 0x93, 0xdf, 0x59, 0x8b, 0x37, 0x00, 0xdf, 0x70, 0x78, 0xde, 0x37, 0x46, 0xb8, 0x7f,
	0x7d, 0x5b, 0x9f, 0x78, 0xe5, 0xeb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xd5, 0x45, 0x88,
	0xd7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemResolverClient is the client API for ItemResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemResolverClient interface {
	Item(ctx context.Context, in *QueryItemReq, opts ...grpc.CallOption) (*QueryItemRes, error)
	CreateItem(ctx context.Context, in *CreateItemReq, opts ...grpc.CallOption) (*QueryItemRes, error)
}

type itemResolverClient struct {
	cc *grpc.ClientConn
}

func NewItemResolverClient(cc *grpc.ClientConn) ItemResolverClient {
	return &itemResolverClient{cc}
}

func (c *itemResolverClient) Item(ctx context.Context, in *QueryItemReq, opts ...grpc.CallOption) (*QueryItemRes, error) {
	out := new(QueryItemRes)
	err := c.cc.Invoke(ctx, "/item.ItemResolver/Item", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemResolverClient) CreateItem(ctx context.Context, in *CreateItemReq, opts ...grpc.CallOption) (*QueryItemRes, error) {
	out := new(QueryItemRes)
	err := c.cc.Invoke(ctx, "/item.ItemResolver/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemResolverServer is the server API for ItemResolver service.
type ItemResolverServer interface {
	Item(context.Context, *QueryItemReq) (*QueryItemRes, error)
	CreateItem(context.Context, *CreateItemReq) (*QueryItemRes, error)
}

// UnimplementedItemResolverServer can be embedded to have forward compatible implementations.
type UnimplementedItemResolverServer struct {
}

func (*UnimplementedItemResolverServer) Item(ctx context.Context, req *QueryItemReq) (*QueryItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Item not implemented")
}
func (*UnimplementedItemResolverServer) CreateItem(ctx context.Context, req *CreateItemReq) (*QueryItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}

func RegisterItemResolverServer(s *grpc.Server, srv ItemResolverServer) {
	s.RegisterService(&_ItemResolver_serviceDesc, srv)
}

func _ItemResolver_Item_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemResolverServer).Item(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemResolver/Item",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemResolverServer).Item(ctx, req.(*QueryItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemResolver_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemResolverServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemResolver/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemResolverServer).CreateItem(ctx, req.(*CreateItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemResolver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemResolver",
	HandlerType: (*ItemResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Item",
			Handler:    _ItemResolver_Item_Handler,
		},
		{
			MethodName: "CreateItem",
			Handler:    _ItemResolver_CreateItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item.proto",
}
